title: Jakemraz
description: Blog
author: Jakemraz
email: jakemraz100@gmail.com
github_username: jakemraz

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Permalink 설정
permalink: /:year/:month/:day/:title/

# 댓글 설정 (Utterances)
utterances:
  repo: jakemraz/jakemraz.github.io
  issue_term: pathname
  theme: github-light

# 타임존
timezone: Asia/Seoul

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock