title: Jakemraz
description: Always Day 1. Jakemraz의 기술 블로그
author: Jakemraz
email: jakemraz100@gmail.com
github_username: jakemraz
url: "https://jakemraz.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Permalink 설정
permalink: /:year/:month/:day/:title/

# 댓글 설정 (Utterances)
utterances:
  repo: jakemraz/jakemraz.github.io
  issue_term: pathname
  theme: github-light

# 타임존
timezone: Asia/Seoul

# SEO 설정
lang: ko_KR
social:
  name: Jakemraz
  links:
    - https://github.com/jakemraz

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock